name: frontend
description: 팬 공장 생산관리 프로그램.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.4.12

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  dio: ^4.0.6
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.1.0
  go_router: ^3.0.5
  hooks_riverpod: ^1.0.3
  image_picker: ^0.8.4+11
  image_picker_for_web: ^2.1.8
  intl: ^0.17.0
  logging: ^1.0.2
  package_info_plus: ^1.4.2
  path: ^1.8.0
  path_provider: ^2.0.9
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.4
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: 
  flutter_gen_runner:
  freezed: 
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.9.2

# Icon generator
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# generated file configuration
flutter_gen:
  output: lib/src/core/presentation/

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets: 
    - assets/images/
    - assets/fonts/
  fonts:
    - family: InspectIcon
      fonts:
        - asset: assets/fonts/Icons/InspectIcon.ttf

    - family: Maruburi
      fonts:
        - asset: assets/fonts/maruburi/MaruBuri-Regular.ttf
        - asset: assets/fonts/maruburi/MaruBuri-Bold.ttf
          weight: 900
        - asset: assets/fonts/maruburi/MaruBuri-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/maruburi/MaruBuri-Light.ttf
          weight: 300
        - asset: assets/fonts/maruburi/MaruBuri-SemiBold.ttf
          weight: 700

    - family: Iropke
      fonts:
        - asset: assets/fonts/iropke/IropkeBatangM.ttf

    - family: NanumBarunPen
      fonts:
        - asset: assets/fonts/nanum-barun-pen/NanumBarunpenR.ttf
        - asset: assets/fonts/nanum-barun-pen/NanumBarunpenB.ttf
          weight: 700